encoding: 'utf-8'

# SITE
lang: en

title: 01-boilerplate
short_name: 01bp

description: >-
  The ‘CSS Tricks’ Inspired Framework

# The base hostname & protocol for the site without a trailing slash,
# e.g. https://example.tld
url: https://01-boilerplate.super-mark.ru

# the subpath of the site, e.g. /blog
baseurl: ''
assets: /assets
image: /img/cover.png
icon: /img/icon-192.png
logo: /img/logo.png
fonts: Fira+Code&family=Roboto:wght@400;500

color: '#5d5de5'

gtm: false
apple_app_id: false

# Site content creator / author Twitter @username
author: '@supervova'

permalink: /:slug

# Ruby Date Format
date_format: '%-d %B, %Y'
timezone: Europe/Podgorica

livereload: true

# ------------------------------------------------------------------------------

# Advanced Settings

theme: null

# Extended markdown letting use CSS classes: {:.btn .btn–primary}
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Default front matter values
defaults:
  -
    scope:
      path: ''
      type: pages # all pages
    values:
      layout: page
      lang: en

# Exclude from processing.
# We use underscore prefix in js/[_base, _how-to] to prevent the processing
# of the folder contents into multiple files but using it as trigger for jekyll
# build.
exclude:
  - '*.pug'
  - .jekyll-assets-cache
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - _tmp
  - deploy.sh
  - gemfiles
  - gulpfile*
  - node_modules
  - package.json
  - readme.md
  - src
  - todo.md
  - yarn-error.log
  - yarn.lock
  - '*~.*'
  - backup


keep_files:
  - .git
  - assets/css
  - assets/img
  - assets/js

# Plugins
plugins:
  # GitHub Pages uses the following dependencies and versions
  # https://pages.github.com/versions/
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-feed
  # - jekyll-paginate

# Plugins incompatible with the GitHub Pages:
  # - jekyll-email-protect
  # - jekyll-include-cache
  # - jekyll-paginate-v2
  # - jekyll-tidy

# See polylog 2020 and super-mark for more settings:
# collections
# feed
# Pagination Settings
# HTML Compression
# Netlify directives
# jekyll_tidy plugin settings
